version: '3.8'
services:
  mongodb:
    image: 'mongo'
    # container_name: mongodb
    volumes:
      - data:/data/db
    env_file:
      - ./env/mongo.env
  backend:
    build: ./backend
    image: 'goals-node'
    ports:
      - '80:80'
    volumes:
      - logs:/app/logs      # named volume
      - ./backend:/app      # bin mount, compose에서는 상대경로 이용
      - /app/node_modules   # anonymous volume
    env_file:
      - ./env/backend.env
    depends_on:
      - mongodb
  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    volumes:
      -./frontend/src:/app/src
    stdin_open: true # -i
    tty: true        # -t   
    depends_on:
      - backend

volumes:
  data:
  logs: